name: Daniel Mulroy
favicon: null
layout_spectrum: 0.11693216534331441
typography_spectrum: 0.9029574790038168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7128908750601113
  lightness: 0.9021601958665997
  saturation: 0.10140967322513461
  rhythmicContrast: 0.0360531413462013
purpose: []
